apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: tls-watch-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 2610
      targetPort: 2610
      nodePort: 32610
  selector:
    app: tls-watch-api