name: Run SSL Expiry Watch

on:
  schedule:
    - cron: '23 4 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Pull Docker image
      run: docker pull ghcr.io/rajkumaar23/ssl-expiry-watch:main

    - name: Set up configuration
      run: echo "$CONFIG_JSON" > config.json
      env:
        CONFIG_JSON: ${{ secrets.CONFIG_JSON }}

    - name: Run Docker container
      run: docker run -v "$(pwd)/config.json:/app/config.json" ghcr.io/rajkumaar23/ssl-expiry-watch:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
